commit

diff --git a/.github/workflows/pipeline-backend.yml b/.github/workflows/pipeline-backend.yml
--- a/.github/workflows/pipeline-backend.yml
+++ b/.github/workflows/pipeline-backend.yml
@@ -4,15 +4,11 @@ on:
   push:
     branches:
       - main
-    paths:
-      - book-management/**
-      - docker/backend/**
-      - "docker-compose.yml"
-      - .github/workflows/*-backend.yml
 
 jobs:
   compile:
-    runs-on: self-hosted
+    runs-on: ubuntu-latest
+    if: "!contains(github.event.head_commit.message, 'skip')"
     name: Compile project
     steps:
       - name: Checkout code
@@ -26,13 +22,14 @@ jobs:
           java-version: "17"
           distribution: "corretto"
 
-      - name: Running Unit Tests
+      - name: Compile project
         run: |
           cd book-management
+          chmod +x ./mvnw
           ./mvnw clean compile
 
   unit-tests:
-    runs-on: self-hosted
+    runs-on: ubuntu-latest
     name: Unit tests
     steps:
       - name: Checkout code
@@ -46,13 +43,14 @@ jobs:
           java-version: "17"
           distribution: "corretto"
 
-      - name: Running Unit Tests
+      - name: Run Unit Tests
         run: |
           cd book-management
+          chmod +x ./mvnw
           ./mvnw clean test
 
   build:
-    runs-on: self-hosted
+    runs-on: ubuntu-latest
     name: Build backend
     needs: [compile, unit-tests]
     steps:
@@ -70,17 +68,17 @@ jobs:
       - name: Compile project
         run: |
           cd book-management
+          chmod +x ./mvnw
           ./mvnw clean compile
 
-  deploy:
-    name: Deploy to Render
-    runs-on: self-hosted
-    needs: [build]
-    steps:
-      - name: Trigger Render Deploy
-        env:
-          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
-        run: |
-          if (-not $env:deploy_url) { Write-Error "Error: deploy_url is not set"; exit 1 }
-          Invoke-WebRequest -Uri $env:deploy_url
-  
+  # deploy:
+  #   name: Deploy to Render
+  #   runs-on: ubuntu-latest
+  #   needs: [build]
+  #   steps:
+  #     - name: Trigger Render Deploy
+  #       env:
+  #         deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
+  #       run: |
+  #         if [ -z "$deploy_url" ]; then echo "Error: deploy_url is not set"; exit 1; fi
+  #         curl -X GET "$deploy_url"
